### ISSUE TITLE
When will you publish the new version of react-progress-bar.js in npm?

### ISSUE THREAD

**Issue by abdurrahmanekr** [squarecat/react-progressbar.js#6]

**Comment by Jivings** [comment]
Thanks for the reminder, it's done.

<img width="334" alt="screen shot 2018-04-02 at 11 45 56" src="https://user-images.githubusercontent.com/1462828/38178660-7b6ea3f0-366b-11e8-8adf-16b130c4b2bb.png">

**Comment by abdurrahmanekr** [comment]
Thanks. I think dist/react-progressbar.js has not been updated. 
src/main.js render method:
![1](https://user-images.githubusercontent.com/15075759/38183373-8e6de150-3648-11e8-80c9-15ac36814979.png)

dist/react-progressbar.js render method:
![2](https://user-images.githubusercontent.com/15075759/38183391-b59db034-3648-11e8-91df-a65d1d0f4e4d.png)

containerClassName prop not exists.

**Comment by Jivings** [comment]
@abdurrahmanekr Sorry my mistake, try it now.

<img width="286" alt="screen shot 2018-04-02 at 17 08 41" src="https://user-images.githubusercontent.com/1462828/38183984-8569a06c-3698-11e8-8c44-283bb9927c31.png">

https://github.com/squarecat/react-progressbar.js/blob/master/dist/react-progressbar.js#L109
