### ISSUE TITLE
Some differences.

### ISSUE THREAD

**Issue by abdurrahmanekr** [squarecat/react-progressbar.js#7]
Hi. Do not they have to be equal to each other?
**containerStyle
containerClassName**

**Fork:**
https://github.com/squarecat/react-progressbar.js/blob/9ccccb63f5aacaee1809f2cf619b783e70c2d696/src/main.js#L25-L29

**Base:**
https://github.com/kimmobrunfeldt/react-progressbar.js/blob/8b3c551ce534e4d189ae3cc2821a67b453cac8d5/src/main.js#L25-L30

**Comment by abdurrahmanekr** [comment]
I actually meant that "containerStyle" was used here as "style". Because it says "containerStyle" in the document and it will break other dependents.
![1](https://user-images.githubusercontent.com/15075759/38229604-37f24aa8-3712-11e8-98b1-40a04601d1c0.png)
 If you want, I can open a PR for this

**Comment by Jivings** [comment]
Sure, open a PR.
