### ISSUE TITLE
React 16 compatibility

### ISSUE THREAD

**Issue by indapublic** [squarecat/react-progressbar.js#9]
`react-progressbar.js` has `react@15.0.1` as it dependency. Could you update your component for React 16 using? Right now I have error:

> Uncaught Error: Element ref was specified as a string (progressBar) but no owner was set. This could happen for one of the following reasons:
> 1. You may be adding a ref to a functional component
> 2. You may be adding a ref to a component that was not created inside a component's render method
> 3. You have multiple copies of React loaded

**Comment by cangoektas** [comment]
`react-progressbar.js` is not maintained anymore. @Jivings forked the repo and republished it under the name `react-progress-bar.js`. This here is the fork. You should be able to switch to that module which is already compatible with React 16. Also, feel free to submit a PR to update the README and make this a bit more clear. :)

**Comment by indapublic** [comment]
Hm. One dash:) OK, thanks
